### ISSUE TITLE
Bring initial coverage up to 100%

### ISSUE THREAD

**Issue by devinivy** [hapijs/validate#1]
As described in https://github.com/sideway/joi/issues/2411, the hapi ecosystem will no longer depend directly on joi (although it will continue to support joi schemas in route validations).  In order to satisfy our internal validation needs we still need a validation library, though!  Eran has culled the joi codebase to remove features that we have no need to maintain for our internal purposes, and that is what you find here.

The test suite is fully passing, but coverage for this module began at ~97% with ~150 uncovered lines of code.  We would like to bring it up to 100% so that it is in line with our typical standards.  This is a tracking issue _for anyone interested in contributing to this module's coverage_.  We could use the help!

I will be posting updates here to the module's coverage.  If you want to cover some specific lines, or the lines in a particular file, just post here so we can organize around each other.  Make any PRs to the branch named [`initial-coverage`](https://github.com/hapijs/validate/tree/initial-coverage), and please prefer to add tests over adjusting the codebase.

### Coverage report
> This will be edited as PRs are merged in order to remain up-to-date.
> There are ~156~ ~130~ ~125~ ~94~ ~60~ ~41~ ~33~ ~20~ ~16~ **10** remaining lines to cover.

```
Coverage: 99.81% (10/5373)
[in-progress] lib/errors.js missing coverage on line(s): 55, 59, 60, 115, 116, 149
[in-progress] lib/modify.js missing coverage on line(s): 101, 168, 183, 184
Code coverage below threshold: 99.81 < 100
```

**Comment by zemccartney** [comment]
@devinivy yo! I'd love to take a shot at helping with this, down for whatever. Any lines in particular you'd prefer I take? I'm also happy to pick a handful at random and post here, whatever's easiest. Thanks!

**Comment by devinivy** [comment]
@zemccartney sweet, thanks! Just pick some lines or a file and post them here :)

**Comment by zemccartney** [comment]
woo! cool, thanks! I'll take a shot at `lib/types/string.js` 🙏

**Comment by watofundefined** [comment]
Hey, I'll do the `common.js`.

**Comment by patlehmann1** [comment]
I'll try grabbing `lib/values.js`

**Comment by WesTyler** [comment]
I've got a PR [here](https://github.com/hapijs/validate/pull/3) for `lib/messages.js` coverage.

**Comment by devinivy** [comment]
Just want to say this has been going great— thanks for all the help everyone.  We have fewer than 100 lines left and are at over 98% coverage 👍 👍

**Comment by WesTyler** [comment]
I'll see if I can grab some time today/tomorrow to cover `lib/types/keys.js`

**Comment by giovanebribeiro** [comment]
I'll make the `lib/errors.js` coverage

**Comment by geek** [comment]
I'm working on lib/template.js

**Comment by Marsup** [comment]
Shouldn't a PR be started with what you already have so that reviews can come in early ?

**Comment by geek** [comment]
Here is the [PR](https://github.com/hapijs/validate/pull/5) for template coverage. This also improved ref and some other areas, current coverage with PR:

```
Coverage: 98.62% (75/5435)
lib/base.js missing coverage on line(s): 611, 673, 677, 720
lib/compile.js missing coverage on line(s): 200
lib/errors.js missing coverage on line(s): 55, 59, 60, 75, 115, 116, 149
lib/modify.js missing coverage on line(s): 37, 38, 78, 101, 168, 183, 184
lib/ref.js missing coverage on line(s): 237, 334, 335
lib/values.js missing coverage on line(s): 46, 82-84
lib/types/array.js missing coverage on line(s): 230, 232-234, 405, 406, 455, 617, 618, 625-627, 630
lib/types/keys.js missing coverage on line(s): 129, 190, 206, 346, 398, 410, 411, 771, 772, 775, 776, 877, 878, 888, 892
lib/types/string.js missing coverage on line(s): 663, 664, 669-672, 692, 693, 700, 701, 718, 719, 722, 723, 743, 744, 747, 748, 752, 753, 773
```

**Comment by Nargonath** [comment]
I'll work on `lib/modify.js`

**Comment by devinivy** [comment]
We're now over 99%.  I am taking lib/base.js, lib/compile.js, and lib/ref.js.  Now all lines are accounted for, but if you picked-up some lines and find that you don't have capacity to complete them, of course no problem— just let us know.

**Comment by devinivy** [comment]
A few more PRs have landed and we're getting very close: just 16 lines left to cover.  Some light pings just to make sure nothing is getting lost:

@Nargonath are you still working through `lib/modify.js`?
@giovanebribeiro are you still working through `lib/errors.js`?
@WesTyler there are two lines left in `lib/types/keys.js`— are you still interested in working on those?

There's no pressure here!  Just looking for a. "I am working on it and would like to see it through," b. "I am working on it but I am currently stuck," or c. "I don't have time to work on it or would rather not work on it anymore" and we can go from there :) You can also reach out to me about this in the hapi hour Slack if you'd like.

**Comment by Nargonath** [comment]
I'm still working on lib/modify.js and I'd like to see it through but I'll comment the issue in case I get nowhere with the tests.

**Comment by giovanebribeiro** [comment]
Hello @devinivy ,

My option is currently this one: b. "I am working on it but I am currently stuck,". I will reach you on slack for some questions
